resources:
  - name: automation
    type: git
    source:
      uri: https://github.com/chivince/deploy-automation.git
      branch: master
      private_key: ((github-private-key))
  - name: config
    type: git
    source:
      uri: https://github.com/chivince/deploy-config.git
      branch: master
      private_key: ((github-private-key))
  - name: ci-image
    type: registry-image
    icon: docker
    source: { repository: busybox }

jobs:
  - name: deploy
    serial: true
    plan:
      - in_parallel:
        - get: automation
        - get: config
        - get: ci-image
      - task: deploy
        image: ci-image
        params:
          COLOR: ((color))
          ENV_NAME: sandbox
          VERSION: ((component-version))
        config:
          platform: linux
          run:
            path: sh
            args:
              - -ec
              - |
                sleep 2
                echo "Color  : $COLOR"
                sleep 2
                echo "EnvName: $ENV_NAME"
                sleep 2
                echo "Version: $VERSION"
