---
platform: linux

inputs:
  - name: automation

outputs:
  - name: prepared-pipeline

params:
  ENV_NAME:

run:
  path: sh
  args:
    - -ec
    - |
      automation/ci/repipe/tasks/prepare-pipeline.sh
      
