resources:
  - name: automation
    type: git
    source:
      uri: https://github.com/chivince/deploy-automation.git
      branch: master
  - name: config
    type: git
    source:
      uri: https://github.com/chivince/deploy-config.git
      branch: master
  - name: ci-image
    type: registry-image
    icon: docker
    source: { repository: busybox }

jobs:
  - name: repipe-sandbox
    plan:
      - in_parallel:
        - get: automation
        - get: config
        - get: ci-image
      - set_pipeline: sandbox-pipeline
        file: automation/ci/deploy-infra/deploy-pipeline.yml
        vars:
          env_name: sandbox
          next_env: staging
          source_branch: master
        var_files:
          - config/sandbox/settings.yml
          - automation/ci/deploy-infra/config/versions.yml

  - name: repipe-staging
    plan:
      - in_parallel:
        - get: automation
        - get: config
        - get: ci-image
      - set_pipeline: staging-pipeline
        file: automation/ci/deploy-infra/deploy-pipeline.yml
        vars:
          env_name: staging
          next_env: prod
          source_branch: staging
        var_files:
          - config/staging/settings.yml
          - automation/ci/deploy-infra/config/versions.yml

  - name: repipe-prod
    plan:
      - in_parallel:
        - get: automation
        - get: config
        - get: ci-image
      - set_pipeline: prod-pipeline
        file: automation/ci/deploy-infra/deploy-pipeline.yml
        vars:
          env_name: prod
          source_branch: prod
        var_files:
          - config/prod/settings.yml
          - automation/ci/deploy-infra/config/versions.yml
