resources:
  - name: automation
    type: git
    source:
      uri: https://github.com/chivince/deploy-automation.git
      branch: master
  - name: config
    type: git
    source:
      uri: https://github.com/chivince/deploy-config.git
      branch: master
  - name: ci-image
    type: registry-image
    icon: docker
    source: { repository: busybox }

jobs:
  - name: repipe-sandbox
    plan:
      - in_parallel:
        - get: automation
        - get: config
        - get: ci-image
      - set_pipeline: sandbox-pipeline
        file: automation/ci/deploy-infra/deploy-pipeline.yml
        vars:
          ENV_NAME: sandbox
        var_files:
          - config/sandbox/settings.yml
          - automation/ci/deploy-infra/config/versions.yml
